name: build_and_test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libyara-dev

      - name: Install Zig Compiler
        uses: mlugg/setup-zig@v1
        with:
          version: 0.11.0

      - name: Set up Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Execute Unified Master Build Script
        run: |
          chmod +x ./build_scripts/compile_all.sh
          ./build_scripts/compile_all.sh
